name: Test package

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
            auto-activate-base: true
            activate-environment: ""
      - name: Setup environment
        run: |
            make environment
      - name: Lint package
        run: conda run -n tcr-pmhc-interface-analysis make lint
      - name: Test package
        run: conda run -n tcr-pmhc-interface-analysis make test